set(upper_dir "${CMAKE_CURRENT_LIST_DIR}/..")
set(firmware_dir "${upper_dir}/../yyb_stm32")

function(require_file path)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "missing Task 12 file: ${path}")
    endif()
endfunction()

function(require_text path needle)
    file(READ "${path}" content)
    string(FIND "${content}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "missing '${needle}' in ${path}")
    endif()
endfunction()

set(debug "${firmware_dir}/host_protocol/host_debug.c")
set(safety "${firmware_dir}/host_protocol/host_safety.c")
set(commands "${firmware_dir}/host_protocol/host_commands.c")
set(pwm "${firmware_dir}/Hardware/PWM.c")
set(pwm_h "${firmware_dir}/Hardware/PWM.h")
set(uart5 "${firmware_dir}/lanya/usart5.c")
set(project "${firmware_dir}/USER/Template.uvprojx")

foreach(name host_uart3.h host_uart3.c host_time.h host_time.c host_debug.h host_debug.c)
    require_file("${firmware_dir}/host_protocol/${name}")
endforeach()
require_text("${safety}" "PWM_StopAll();")
require_text("${safety}" "Emm_V5_Stop_Now(address, false);")
require_text("${pwm}" "void PWM_StopAll(void)")
require_text("${pwm}" "void set_zhuashou_Angle_NonBlocking")
require_text("${pwm_h}" "set_zhuashou_Angle_NonBlocking")
require_text("${debug}" "set_zhuashou_Angle_NonBlocking")
file(READ "${debug}" debug_content)
string(FIND "${debug_content}" "set_zhuashou_he(" blocking_close)
string(FIND "${debug_content}" "set_zhuashou_kai(" blocking_open)
if(NOT blocking_close EQUAL -1 OR NOT blocking_open EQUAL -1)
    message(FATAL_ERROR "protocol debug path calls blocking gripper API")
endif()
require_text("${uart5}" "UART5_TX_QUEUE_SIZE")
require_text("${uart5}" "UART5_TxPump")
require_text("${uart5}" "void find_congji()")
require_text("${uart5}" "void fasong_task_code(void)")
require_text("${commands}" "HostSafety_IsActiveLink(link)")
require_text("${commands}" "link == HOST_LINK_BLUETOOTH")
require_text("${project}" "..\\host_protocol")
require_text("${project}" "<GroupName>host_protocol</GroupName>")
file(READ "${project}" project_content)
string(REGEX MATCHALL "<FilePath>..\\\\host_protocol\\\\(host_uart3|host_time|host_debug)\\.(c|h)</FilePath>" project_entries "${project_content}")
list(LENGTH project_entries entry_count)
if(NOT entry_count EQUAL 6)
    message(FATAL_ERROR "expected six Task 12 project entries, got ${entry_count}")
endif()
message(STATUS "Task 12 repair static checks: PASS")
