set(upper_dir "${CMAKE_CURRENT_LIST_DIR}/..")
set(firmware_dir "${upper_dir}/../yyb_stm32")

function(require_file path)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "missing Task 12 file: ${path}")
    endif()
endfunction()

function(require_text path needle)
    file(READ "${path}" content)
    string(FIND "${content}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "missing '${needle}' in ${path}")
    endif()
endfunction()

set(debug "${firmware_dir}/host_protocol/host_debug.c")
set(safety "${firmware_dir}/host_protocol/host_safety.c")
set(commands "${firmware_dir}/host_protocol/host_commands.c")
set(main_c "${firmware_dir}/USER/main.c")
set(pwm "${firmware_dir}/Hardware/PWM.c")
set(pwm_h "${firmware_dir}/Hardware/PWM.h")
set(uart5 "${firmware_dir}/lanya/usart5.c")
set(project "${firmware_dir}/USER/Template.uvprojx")

foreach(name host_uart3.h host_uart3.c host_time.h host_time.c host_debug.h host_debug.c
             host_runtime.h host_runtime.c)
    require_file("${firmware_dir}/host_protocol/${name}")
endforeach()
require_text("${safety}" "PWM_StopAll();")
require_text("${safety}" "Emm_V5_Stop_Now(address, false);")
require_text("${pwm}" "void PWM_StopAll(void)")
require_text("${pwm}" "void set_zhuashou_Angle_NonBlocking")
require_text("${pwm_h}" "set_zhuashou_Angle_NonBlocking")
require_text("${debug}" "set_zhuashou_Angle_NonBlocking")
file(READ "${debug}" debug_content)
string(FIND "${debug_content}" "set_zhuashou_he(" blocking_close)
string(FIND "${debug_content}" "set_zhuashou_kai(" blocking_open)
if(NOT blocking_close EQUAL -1 OR NOT blocking_open EQUAL -1)
    message(FATAL_ERROR "protocol debug path calls blocking gripper API")
endif()
require_text("${uart5}" "UART5_TX_QUEUE_SIZE")
require_text("${uart5}" "USART_IT_TXE")
require_text("${uart5}" "UART5_QueueTx")
require_text("${uart5}" "__get_PRIMASK")
require_text("${uart5}" "USART_ITConfig(UART5, USART_IT_TXE, ENABLE)")
file(READ "${uart5}" uart5_content)
string(FIND "${uart5_content}" "while (USART_GetFlagStatus(UART5, USART_FLAG_TC)" polling_tc)
if(NOT polling_tc EQUAL -1)
    message(FATAL_ERROR "UART5 still polls TC")
endif()
string(FIND "${uart5_content}" "USART_ITConfig(UART5, USART_IT_RXNE, DISABLE)" rx_disable)
if(NOT rx_disable EQUAL -1)
    message(FATAL_ERROR "UART5 disables RXNE in ISR")
endif()
require_text("${uart5}" "void find_congji()")
require_text("${uart5}" "void fasong_task_code(void)")
require_text("${commands}" "HostSafety_IsActiveLink(link)")
require_text("${commands}" "actual_rate > 50u")
require_text("${main_c}" "uart5_init(115200);")
require_text("${debug}" "HOST_DEBUG_RX_BYTE_BUDGET")
require_text("${debug}" "HOST_DEBUG_FRAME_BUDGET")
require_text("${debug}" "HostSafety_Tick(now)")
set(config "${firmware_dir}/host_protocol/host_config.h")
require_text("${config}" "#ifndef HOST_DEBUG_MODE")
require_text("${config}" "#define HOST_DEBUG_MODE 1")
set(pid_stub "${CMAKE_CURRENT_LIST_DIR}/stubs/task12/pid.h")
set(params_h "${firmware_dir}/host_protocol/host_params.h")
require_text("${pid_stub}" "HOST_PID_PROFILE_T_DEFINED")
require_text("${params_h}" "HOST_PID_PROFILE_T_DEFINED")
require_text("${project}" "..\\host_protocol")
require_text("${project}" "<GroupName>host_protocol</GroupName>")
file(READ "${project}" project_content)
string(REGEX MATCHALL "<FilePath>..\\\\host_protocol\\\\(host_uart3|host_time|host_debug)\\.(c|h)</FilePath>" project_entries "${project_content}")
list(LENGTH project_entries entry_count)
if(NOT entry_count EQUAL 6)
    message(FATAL_ERROR "expected six Task 12 project entries, got ${entry_count}")
endif()
set(host_protocol_files
    host_config.h host_crc16.c host_crc16.h host_frame.c host_frame.h
    host_link.c host_link.h host_params.c host_params.h host_safety.c
    host_safety.h host_commands.c host_commands.h host_uart3.c host_uart3.h
    host_time.c host_time.h host_debug.c host_debug.h)
foreach(name IN LISTS host_protocol_files)
    string(REGEX MATCHALL "<FilePath>..\\\\host_protocol\\\\${name}</FilePath>" matches "${project_content}")
    list(LENGTH matches count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "expected exactly one Keil entry for ${name}, got ${count}")
    endif()
endforeach()
message(STATUS "Task 12 repair static checks: PASS")
